#include "driver/i2c_slave.h"
#include "esp_log.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"
#include "freertos/queue.h"

#include <string.h>
#include <stdint.h>

#define I2C_SLAVE_PORT       I2C_NUM_0
#define I2C_SLAVE_SDA        GPIO_NUM_18
#define I2C_SLAVE_SCL        GPIO_NUM_19
#define I2C_SLAVE_ADDRESS    0x12

static const char *TAG = "I2C";

static i2c_slave_dev_handle_t slave_handle = NULL;
static QueueHandle_t i2c_rx_queue = NULL;

extern void app_command(uint8_t command);

//These are supplied by main.c.
extern int app_get_current_track(void);
extern int app_get_track_count(void);
extern const char *app_get_current_track_name(void);
extern bool app_get_random_playback(void);
extern uint8_t app_get_playback_status(void);


// -------------------------------------------------------
// Commands: S3 -> WROVER
// -------------------------------------------------------

#define CMD_PREV        0x01
#define CMD_PLAYPAUSE   0x02
#define CMD_NEXT        0x03
#define CMD_SHUFFLE     0x04
#define CMD_STATUS      0x10

#define STATUS_PACKET   0x30

#define PACKET_STATUS_STOPPED   0x00
#define PACKET_STATUS_PLAYING   0x01
#define PACKET_STATUS_PAUSED    0x02

#define MODE_SEQUENTIAL 0x00
#define MODE_RANDOM     0x01

#define STATUS_PACKET_SIZE 32
#define I2C_EVENT_STATUS_REQUEST 0xFF

static uint8_t status_packet[STATUS_PACKET_SIZE];

// -------------------------------------------------------
// Build status packet
// -------------------------------------------------------
static void build_status_packet(void)
{
    memset(status_packet, 0, sizeof(status_packet));

    status_packet[0] = STATUS_PACKET;
    status_packet[1] = app_get_playback_status();
    status_packet[2] =
        app_get_random_playback()
        ? MODE_RANDOM
        : MODE_SEQUENTIAL;

    int track = app_get_current_track();
    int count = app_get_track_count();

    status_packet[3] = track & 0xFF;
    status_packet[4] = (track >> 8) & 0xFF;
    status_packet[5] = count & 0xFF;
    status_packet[6] = (count >> 8) & 0xFF;

    const char *name = app_get_current_track_name();

    if (name != NULL)
    {
        strncpy(
            (char *)&status_packet[7],
            name,
            STATUS_PACKET_SIZE - 8
        );
    }
}

/* -------------------------------------------------------
// I2C READ REQUEST CALLBACK
// -------------------------------------------------------
static bool IRAM_ATTR i2c_request_callback(
    i2c_slave_dev_handle_t handle,
    const i2c_slave_request_event_data_t *evt_data,
    void *arg)
{
    BaseType_t high_task_wakeup = pdFALSE;

    uint8_t event = 0xFF;

    xQueueSendFromISR(
        i2c_rx_queue,
        &event,
        &high_task_wakeup
    );

    return high_task_wakeup == pdTRUE;
}
*/
// -------------------------------------------------------
// I2C RX CALLBACK
// -------------------------------------------------------
static bool IRAM_ATTR i2c_rx_callback(
    i2c_slave_dev_handle_t handle,
    const i2c_slave_rx_done_event_data_t *evt_data,
    void *arg)
{
    BaseType_t high_task_wakeup = pdFALSE;

    if (evt_data != NULL &&
        evt_data->buffer != NULL &&
        evt_data->length > 0)
    {
        uint8_t command = evt_data->buffer[0];

        xQueueSendFromISR(
            i2c_rx_queue,
            &command,
            &high_task_wakeup
        );
    }
    return high_task_wakeup == pdTRUE;
}

// -------------------------------------------------------
// I2C TASK
// -------------------------------------------------------
static void i2c_rx_task(void *arg)
{
    uint8_t event;

    ESP_LOGI(TAG, "I2C task started");

    while (1)
    {
        if (xQueueReceive(
                i2c_rx_queue,
                &event,
                portMAX_DELAY) != pdTRUE)
        {
            continue;
        }

        // Internal event generated by an I2C master read request
        if (event == I2C_EVENT_STATUS_REQUEST)
        {
            ESP_LOGI(TAG, "I2C STATUS REQUEST");

            build_status_packet();

            uint32_t written = 0;

            esp_err_t err = i2c_slave_write(
                slave_handle,
                status_packet,
                STATUS_PACKET_SIZE,
                &written,
                100
            );

            if (err != ESP_OK)
            {
                ESP_LOGW(TAG, "Status TX failed: %s", esp_err_to_name(err));
            }
            else
            {
                ESP_LOGI(TAG, "STATUS TX: %lu bytes", (unsigned long)written);

                ESP_LOG_BUFFER_HEX(TAG, status_packet, STATUS_PACKET_SIZE);
            }
            continue;
        }

        uint8_t command = event;

        if (command != 0x10)
        {
            ESP_LOGI(TAG, "I2C RX: 0x%02X", command);
        }
        //ESP_LOGI(TAG, "I2C RX: 0x%02X", command);

        switch (command)
        {
            case CMD_PREV:
                ESP_LOGI(TAG, "COMMAND: PREVIOUS");
                app_command(CMD_PREV);
                break;

            case CMD_PLAYPAUSE:
                ESP_LOGI(TAG, "COMMAND: PLAY/PAUSE");
                app_command(CMD_PLAYPAUSE);
                break;

            case CMD_NEXT:
                ESP_LOGI(TAG, "COMMAND: NEXT");
                app_command(CMD_NEXT);
                break;

            case CMD_SHUFFLE:
                ESP_LOGI(TAG, "COMMAND: SHUFFLE");
                app_command(CMD_SHUFFLE);
                break;

            case CMD_STATUS:
                //ESP_LOGI(TAG, "COMMAND: STATUS REQUEST");
                build_status_packet();
                uint32_t written = 0;
                esp_err_t err = i2c_slave_write(
                    slave_handle,
                    status_packet,
                    STATUS_PACKET_SIZE,
                    &written,
                    100
                );

                if (err != ESP_OK)
                {
                    ESP_LOGW(TAG, "Status TX failed: %s", esp_err_to_name(err));
                }
                else
                {
                    //ESP_LOGI(TAG, "STATUS TX queued: %lu bytes", (unsigned long)written);
                }

                break;

            default:
                ESP_LOGW(TAG, "Unknown command: 0x%02X", command);
                break;
        }
    }
}

// -------------------------------------------------------
// INIT
// -------------------------------------------------------
void i2c_slave_init(void)
{
    i2c_slave_config_t config = {

        .i2c_port = I2C_SLAVE_PORT,
        .sda_io_num = I2C_SLAVE_SDA,
        .scl_io_num = I2C_SLAVE_SCL,
        .clk_source = I2C_CLK_SRC_DEFAULT,
        .send_buf_depth = 64,
        .receive_buf_depth = 64,
        .slave_addr = I2C_SLAVE_ADDRESS,
        .addr_bit_len = I2C_ADDR_BIT_LEN_7,
        .intr_priority = 0,
        .flags = {
            .allow_pd = 0,
            .enable_internal_pullup = 0,
        },
    };

    ESP_ERROR_CHECK(
        i2c_new_slave_device(
            &config,
            &slave_handle
        )
    );

    ESP_LOGI(
        TAG,
        "I2C slave started: address=0x%02X SDA=%d SCL=%d",
        I2C_SLAVE_ADDRESS,
        I2C_SLAVE_SDA,
        I2C_SLAVE_SCL
    );

    i2c_rx_queue =
        xQueueCreate(
            16,
            sizeof(uint8_t)
        );

    if (i2c_rx_queue == NULL)
    {
        ESP_LOGE(TAG, "Failed to create I2C RX queue");

        return;
    }

    i2c_slave_event_callbacks_t callbacks = {
        .on_receive = i2c_rx_callback,
        .on_request = NULL,
    };

    ESP_ERROR_CHECK(
        i2c_slave_register_event_callbacks(
            slave_handle,
            &callbacks,
            NULL
        )
    );

    xTaskCreatePinnedToCore(
        i2c_rx_task,
        "i2c_rx",
        4096,
        NULL,
        4,
        NULL,
        0
    );
}